# Generated by Django 3.1 on 2020-10-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fableous.models


class Migration(migrations.Migration):

    dependencies = [
        ('fableous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fableous.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to=fableous.models.upload_to_path)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fableous.story')),
            ],
        ),
    ]
