# Generated by Django 3.1 on 2020-10-27 11:54

from django.db import migrations, models
import fableous.models


class Migration(migrations.Migration):

    dependencies = [
        ('fableous', '0002_story_storypage_storytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='image',
            field=models.ImageField(default=1, upload_to=fableous.models.upload_to_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storypage',
            name='page',
            field=models.IntegerField(),
        ),
    ]
